apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{APP_NAME}}-db-secret
  namespace: {{APP_NAME}}
spec:
  encryptedData:
    username: REPLACE_WITH_SEALED_VALUE
    password: REPLACE_WITH_SEALED_VALUE