apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{APP_NAME}}-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/{{OWNER}}/{{APP_NAME}}-config
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true